[project]
name = "linkedin-sql-nosql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.1.3",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "tinydb>=4.8.2",
]
